from task_loop_functions.auto_concerts import auto_concerts
# from task_loop_functions.auto_standup import auto_standup
from task_loop_functions.auto_weather import auto_weather
# from task_loop_functions.auto_convents import auto_convents
from task_loop_functions.auto_currencies import auto_currencies
# from task_loop_functions.auto_last_minute import auto_last_minute
from task_loop_functions.auto_bus_check_update import auto_bus_check_update
# from task_loop_functions.auto_jobs_old import auto_jobs
# from task_loop_functions.auto_quiz import auto_quiz
from task_loop_functions.async_auto_pracuj import async_auto_pracuj